version: '3.9'
services:
  rabbitmq:
    image: 'rabbitmq:alpine'
    container_name: "rabbitmq"
    ports:
      - '5672:5672'
  ic-train-server:
    build:
      context: .
      dockerfile: Dockerfile.ic-train-server
    environment:
      - RABBITMQ_HOST=rabbitmq
    links:
      - rabbitmq
    ports:
      - '9090:9090'
  ic-train-worker:
    build:
      context: .
      dockerfile: Dockerfile.ic-train-worker
    environment:
      - RABBITMQ_HOST=rabbitmq
    links:
      - rabbitmq
    volumes:
      - /media/data:/media/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
