FROM continuumio/miniconda3

WORKDIR /app

# create conda environment using mamba because it is faster
ENV CONDA_ENV="ic-train-server"
COPY ./environment.${CONDA_ENV}.yml /app
RUN conda install -c conda-forge mamba
RUN mamba env create -f environment.${CONDA_ENV}.yml

EXPOSE 9090

COPY ./src /app

CMD /bin/bash -c ". activate ${CONDA_ENV} && python server.py"
